import CONFIG from './config.js';

// ==========================================
// DICCIONARIO DE TRADUCCIONES
// ==========================================
const traducciones = {
  es: {
    nombreIdioma: "🌐 Español ▼",
    logo: "🌱 remarket-db OS",
    chatPlaceholder: "Escribe tu duda aquí...",
    chatBtn: "Enviar",
    catalogoTitulo: "🌱 Catálogo de Economía Circular",
    catalogoSub: "Descubre artículos disponibles para intercambio en tu zona",
    btnPublicar: "📦 Publicar",
    saludoIA: "¡Hola! Soy tu asistente de economía circular global. ¿Qué necesitas hoy?",
    detectandoUbicacion: "🔍 Detectando tu ubicación y cargando publicaciones...",
    tuAlcance: " Tu Alcance",
    detectandoIP: "Detectando IP...",
    patrocinadores: "Patrocinadores"
  },
  en: {
    nombreIdioma: "🌐 English ▼",
    logo: "🌱 remarket-db OS",
    chatPlaceholder: "Type your question here...",
    chatBtn: "Send",
    catalogoTitulo: "🌱 Circular Economy Catalog",
    catalogoSub: "Discover items available for exchange in your area",
    btnPublicar: "📦 Publish",
    saludoIA: "Hello! I'm your global circular economy assistant. What do you need today?",
    detectandoUbicacion: "🔍 Detecting your location and loading publications...",
    tuAlcance: "📍 Your Reach",
    detectandoIP: "Detecting IP...",
    patrocinadores: "Sponsors"
  },
  zh: {
    nombreIdioma: "🌐 中文 ▼",
    logo: "🌱 remarket-db 操作系统",
    chatPlaceholder: "在这里输入您的问题...",
    chatBtn: "发送",
    catalogoTitulo: "🌱 循环经济目录",
    catalogoSub: "发现您所在地区可用于交换的物品",
    btnPublicar: "📦 发布",
    saludoIA: "你好！我是您的全球循环经济助手。您今天需要什么？",
    detectandoUbicacion: "🔍 正在检测您的位置并加载出版物...",
    tuAlcance: "📍 您的覆盖范围",
    detectandoIP: "正在检测 IP...",
    patrocinadores: "赞助商"
  },
  pt: {
    nombreIdioma: "🌐 Português ▼",
    logo: "🌱 remarket-db OS",
    chatPlaceholder: "Escreva sua dúvida aqui...",
    chatBtn: "Enviar",
    catalogoTitulo: "🌱 Catálogo de Economia Circular",
    catalogoSub: "Descubra artigos disponíveis para troca na sua zona",
    btnPublicar: "📦 Publicar",
    saludoIA: "Olá! Sou seu assistente de economia circular global. O que você precisa hoje?",
    detectandoUbicacion: "🔍 Detectando sua localização e carregando publicações...",
    tuAlcance: "📍 Seu Alcance",
    detectandoIP: "Detectando IP...",
    patrocinadores: "Patrocinadores"
  },
  fr: {
    nombreIdioma: "🌐 Français ▼",
    logo: "🌱 remarket-db OS",
    chatPlaceholder: "Tapez votre question ici...",
    chatBtn: "Envoyer",
    catalogoTitulo: "🌱 Catalogue d'Économie Circulaire",
    catalogoSub: "Découvrez les articles disponibles pour l'échange dans votre zone",
    btnPublicar: "📦 Publier",
    saludoIA: "Bonjour! Je suis votre assistant d'économie circulaire global. Que vous faut-il aujourd'hui?",
    detectandoUbicacion: "🔍 Détection de votre emplacement et chargement des publications...",
    tuAlcance: "📍 Votre Portée",
    detectandoIP: "Détection IP...",
    patrocinadores: "Sponsors"
  },
  de: {
    nombreIdioma: "🌐 Deutsch ▼",
    logo: "🌱 remarket-db OS",
    chatPlaceholder: "Geben Sie Ihre Frage hier ein...",
    chatBtn: "Senden",
    catalogoTitulo: "🌱 Kreislaufwirtschaft Katalog",
    catalogoSub: "Entdecken Sie Artikel zum Tausch in Ihrer Region",
    btnPublicar: " Veröffentlichen",
    saludoIA: "Hallo! Ich bin Ihr globaler Kreislaufwirtschaftsassistent. Was brauchen Sie heute?",
    detectandoUbicacion: "🔍 Standort wird erkannt und Publikationen werden geladen...",
    tuAlcance: " Ihre Reichweite",
    detectandoIP: "IP wird erkannt...",
    patrocinadores: "Sponsoren"
  },
  it: {
    nombreIdioma: "🌐 Italiano ▼",
    logo: "🌱 remarket-db OS",
    chatPlaceholder: "Scrivi la tua domanda qui...",
    chatBtn: "Invia",
    catalogoTitulo: "🌱 Catalogo Economia Circolare",
    catalogoSub: "Scopri articoli disponibili per lo scambio nella tua zona",
    btnPublicar: "📦 Pubblica",
    saludoIA: "Ciao! Sono il tuo assistente di economia circolare globale. Cosa ti serve oggi?",
    detectandoUbicacion: "🔍 Rilevamento della posizione e caricamento pubblicazioni...",
    tuAlcance: "📍 La tua Portata",
    detectandoIP: "Rilevamento IP...",
    patrocinadores: "Sponsor"
  },
  ja: {
    nombreIdioma: "🌐 日本語 ▼",
    logo: "🌱 remarket-db オペレーティングシステム",
    chatPlaceholder: "ここに質問を入力...",
    chatBtn: "送信",
    catalogoTitulo: "🌱 循環型経済カタログ",
    catalogoSub: "お住まいの地域で交換可能なアイテムを発見",
    btnPublicar: "📦 公開",
    saludoIA: "こんにちは！グローバル循環型経済アシスタントです。今日は何が必要ですか？",
    detectandoUbicacion: "🔍 場所を検出して出版物を読み込んでいます...",
    tuAlcance: " あなたのカバレッジ",
    detectandoIP: "IP検出中...",
    patrocinadores: "スポンサー"
  },
  ko: {
    nombreIdioma: " 한국어 ▼",
    logo: "🌱 remarket-db 운영체제",
    chatPlaceholder: "여기에 질문을 입력하세요...",
    chatBtn: "보내기",
    catalogoTitulo: "🌱 순환 경제 카탈로그",
    catalogoSub: "귀하의 지역에서 교환 가능한 항목 발견",
    btnPublicar: "📦 게시",
    saludoIA: "안녕하세요! 글로벌 순환 경제 어시스턴트입니다. 오늘 무엇이 필요하신가요?",
    detectandoUbicacion: "🔍 위치 감지 및 출판물 로딩 중...",
    tuAlcance: " 당신의 범위",
    detectandoIP: "IP 감지 중...",
    patrocinadores: "스폰서"
  },
  ar: {
    nombreIdioma: "🌐 العربية ▼",
    logo: "🌱 remarket-db نظام التشغيل",
    chatPlaceholder: "اكتب سؤالك هنا...",
    chatBtn: "إرسال",
    catalogoTitulo: "🌱 كتالوج الاقتصاد الدائري",
    catalogoSub: "اكتشف العناصر المتاحة للتبادل في منطقتك",
    btnPublicar: "📦 نشر",
    saludoIA: "مرحبا! أنا مساعد الاقتصاد الدائري العالمي. ماذا تحتاج اليوم؟",
    detectandoUbicacion: "🔍 اكتشاف موقعك وتحميل المنشورات...",
    tuAlcance: "📍 نطاقك",
    detectandoIP: "اكتشاف IP...",
    patrocinadores: "الرعاة"
  },
  hi: {
    nombreIdioma: "🌐 हिन्दी ▼",
    logo: " remarket-db ऑपरेटिंग सिस्टम",
    chatPlaceholder: "अपना प्रश्न यहां लिखें...",
    chatBtn: "भेजें",
    catalogoTitulo: " चक्रीय अर्थव्यवस्था कैटलॉग",
    catalogoSub: "अपने क्षेत्र में विनिमय के लिए उपलब्ध वस्तुओं की खोज करें",
    btnPublicar: "📦 प्रकाशित करें",
    saludoIA: "नमस्ते! मैं आपका वैश्विक चक्रीय अर्थव्यवस्था सहायक हूं। आज आपको क्या चाहिए?",
    detectandoUbicacion: "🔍 आपका स्थान पहचान रहे हैं और प्रकाशन लोड हो रहे हैं...",
    tuAlcance: " आपकी पहुंच",
    detectandoIP: "IP पहचान रहे हैं...",
    patrocinadores: "प्रायोजक"
  },
  nl: {
    nombreIdioma: " Nederlands ▼",
    logo: " remarket-db OS",
    chatPlaceholder: "Typ hier uw vraag...",
    chatBtn: "Verzenden",
    catalogoTitulo: "🌱 Circulaire Economie Catalogus",
    catalogoSub: "Ontdek items beschikbaar voor uitwisseling in uw regio",
    btnPublicar: "📦 Publiceren",
    saludoIA: "Hallo! Ik ben uw wereldwijde circulaire economie assistent. Wat heeft u vandaag nodig?",
    detectandoUbicacion: "🔍 Uw locatie detecteren en publicaties laden...",
    tuAlcance: " Uw Bereik",
    detectandoIP: "IP detecteren...",
    patrocinadores: "Sponsors"
  },
  tr: {
    nombreIdioma: "🌐 Türkçe ▼",
    logo: "🌱 remarket-db İşletim Sistemi",
    chatPlaceholder: "Sorunuzu buraya yazın...",
    chatBtn: "Gönder",
    catalogoTitulo: " Döngüsel Ekonomi Kataloğu",
    catalogoSub: "Bölgenizde değişim için mevcut öğeleri keşfedin",
    btnPublicar: "📦 Yayınla",
    saludoIA: "Merhaba! Ben küresel döngüsel ekonomi asistanınız. Bugün neye ihtiyacınız var?",
    detectandoUbicacion: "🔍 Konumunuz algılanıyor ve yayınlar yükleniyor...",
    tuAlcance: "📍 Kapsamınız",
    detectandoIP: "IP algılanıyor...",
    patrocinadores: "Sponsorlar"
  },
  bg: {
    nombreIdioma: "🌐 Български ▼",
    logo: "🌱 remarket-db ОС",
    chatPlaceholder: "Въведете въпроса си тук...",
    chatBtn: "Изпрати",
    catalogoTitulo: "🌱 Каталог на циркулярната икономика",
    catalogoSub: "Открийте артикули за обмен във вашия район",
    btnPublicar: " Публикуване",
    saludoIA: "Здравейте! Аз съм вашият глобален асистент за циркулярна икономика. Какво ви трябва днес?",
    detectandoUbicacion: "🔍 Откриване на местоположението ви и зареждане на публикации...",
    tuAlcance: " Вашият обхват",
    detectandoIP: "Откриване на IP...",
    patrocinadores: "Спонсори"
  },
  qu: {
    nombreIdioma: "🌐 Quechua ▼",
    logo: "🌱 remarket-db Llamk'ay Sistema",
    chatPlaceholder: "Tapuyniykita kaypi qillqay...",
    chatBtn: "Kachay",
    catalogoTitulo: "🌱 Muyuq Economia Qhatu",
    catalogoSub: "Llaqtaykipi tikranapaq kaqkunata taripay",
    btnPublicar: "📦 Qillqay",
    saludoIA: "Allillanchu! Noqaqa global muyuq economia yanapaqmi. Imatataq kunan p'unchaw munanki?",
    detectandoUbicacion: "🔍 Maypi kasqaykita tarispa qillqasqakunata apachkani...",
    tuAlcance: "📍 Qampa chayanan",
    detectandoIP: "IP tarispa...",
    patrocinadores: "Yanapaqkuna"
  },
  ay: {
    nombreIdioma: "🌐 Aymara ▼",
    logo: "🌱 remarket-db Luräwi Sistema",
    chatPlaceholder: "Jiskisamaxa aka qillqt'asma...",
    chatBtn: "Apayaña",
    catalogoTitulo: "🌱 Muyt'awi Economía Uñacht'awi",
    catalogoSub: "Aka markanxa tukuyata uñjaña",
    btnPublicar: "📦 Qillqt'aña",
    saludoIA: "Aski urukipansa! Noqaxa global muyt'awi economía yanapt'ayiriwa. Kunatix jichhüruxa muntaxa?",
    detectandoUbicacion: "🔍 Mayacht'ataskiwa ukat qillqatanaka apthapiskiwa...",
    tuAlcance: "📍 Kamachima",
   
